/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as JournalismRouteImport } from './routes/journalism'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReachRouteImport } from './routes/reach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalismRoute = JournalismRouteImport.update({
  id: '/journalism',
  path: '/journalism',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/grants': typeof GrantsRoute
  '/journalism': typeof JournalismRoute
  '/overview': typeof OverviewRoute
  '/reach': typeof ReachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/grants': typeof GrantsRoute
  '/journalism': typeof JournalismRoute
  '/overview': typeof OverviewRoute
  '/reach': typeof ReachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/grants': typeof GrantsRoute
  '/journalism': typeof JournalismRoute
  '/overview': typeof OverviewRoute
  '/reach': typeof ReachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/environment' | '/grants' | '/journalism' | '/overview' | '/reach'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/environment' | '/grants' | '/journalism' | '/overview' | '/reach'
  id:
    | '__root__'
    | '/'
    | '/environment'
    | '/grants'
    | '/journalism'
    | '/overview'
    | '/reach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvironmentRoute: typeof EnvironmentRoute
  GrantsRoute: typeof GrantsRoute
  JournalismRoute: typeof JournalismRoute
  OverviewRoute: typeof OverviewRoute
  ReachRoute: typeof ReachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journalism': {
      id: '/journalism'
      path: '/journalism'
      fullPath: '/journalism'
      preLoaderRoute: typeof JournalismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentRoute: EnvironmentRoute,
  GrantsRoute: GrantsRoute,
  JournalismRoute: JournalismRoute,
  OverviewRoute: OverviewRoute,
  ReachRoute: ReachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
